name: Release APWorld
on:
  push:
    tags:
      - '**'
jobs:
  release:
    uses: Marsavue/ap-actions/.github/workflows/release-apworld.yml@main
    with:
      apworld-path: worlds/duckgame
      ap-version: '0.6.7'
      python-version: '3.13'